In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [8]:
df = pd.read_csv("hotel_bookings.csv")

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

In [10]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df["deposit_type"]= label_encoder.fit_transform(df["deposit_type"])


In [11]:
df.tail(10)

hotel  is_canceled  lead_time  arrival_date_year  \
119380  City Hotel            0         44               2017   
119381  City Hotel            0        188               2017   
119382  City Hotel            0        135               2017   
119383  City Hotel            0        164               2017   
119384  City Hotel            0         21               2017   
119385  City Hotel            0         23               2017   
119386  City Hotel            0        102               2017   
119387  City Hotel            0         34               2017   
119388  City Hotel            0        109               2017   
119389  City Hotel            0        205               2017   

       arrival_date_month  arrival_date_week_number  \
119380             August                        35   
119381             August                        35   
119382             August                        35   
119383             August                        35   
119384             August                        35   
119385             August                        35   
119386             August                        35   
119387             August                        35   
119388             August                        35   
119389             August                        35   

        arrival_date_day_of_month  stays_in_weekend_nights  \
119380                         31                        1   
119381                         31                        2   
119382                         30                        2   
119383                         31                        2   
119384                         30                        2   
119385                         30                        2   
119386                         31                        2   
119387                         31                        2   
119388                         31                        2   
119389                         29                        2   

        stays_in_week_nights  adults  ...  deposit_type  agent company  \
119380                     3       2  ...             0    9.0     NaN   
119381                     3       2  ...             0   14.0     NaN   
119382                     4       3  ...             0    7.0     NaN   
119383                     4       2  ...             0   42.0     NaN   
119384                     5       2  ...             0  394.0     NaN   
119385                     5       2  ...             0  394.0     NaN   
119386                     5       3  ...             0    9.0     NaN   
119387                     5       2  ...             0    9.0     NaN   
119388                     5       2  ...             0   89.0     NaN   
119389                     7       2  ...             0    9.0     NaN   

       days_in_waiting_list customer_type     adr  \
119380                    0     Transient  140.75   
119381                    0     Transient   99.00   
119382                    0     Transient  209.00   
119383                    0     Transient   87.60   
119384                    0     Transient   96.14   
119385                    0     Transient   96.14   
119386                    0     Transient  225.43   
119387                    0     Transient  157.71   
119388                    0     Transient  104.40   
119389                    0     Transient  151.20   

        required_car_parking_spaces  total_of_special_requests  \
119380                            0                          1   
119381                            0                          0   
119382                            0                          0   
119383                            0                          0   
119384                            0                          2   
119385                            0                          0   
119386                            0                          2   
119387                            0                          4   
119388         

In [12]:
X = df[['lead_time', 'deposit_type', 'total_of_special_requests']]
y = df['is_canceled']

In [13]:
print(X)

        lead_time  deposit_type  total_of_special_requests
0             342             0                          0
1             737             0                          0
2               7             0                          0
3              13             0                          0
4              14             0                          1
...           ...           ...                        ...
119385         23             0                          0
119386        102             0                          2
119387         34             0                          4
119388        109             0                          0
119389        205             0                          2

[119390 rows x 3 columns]


In [14]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 3 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   lead_time                  119390 non-null  int64
 1   deposit_type               119390 non-null  int32
 2   total_of_special_requests  119390 non-null  int64
dtypes: int32(1), int64(2)
memory usage: 2.3 MB


In [15]:
from sklearn.model_selection import train_test_split

X_train , X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=42)


In [16]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)



RandomForestClassifier(random_state=42)

In [17]:
y_pred = model.predict(X_test)
y_pred_proba = model.predict_proba(X_test)

In [18]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.7590

Classification Report:
               precision    recall  f1-score   support

           0       0.74      0.95      0.83     14907
           1       0.83      0.45      0.58      8971

    accuracy                           0.76     23878
   macro avg       0.79      0.70      0.71     23878
weighted avg       0.77      0.76      0.74     23878


Confusion Matrix:
 [[14089   818]
 [ 4937  4034]]


In [22]:
from xgboost import XGBClassifier

model1 = XGBClassifier(n_estimators=200, learning_rate=0.1, max_depth=7, use_label_encoder=False, eval_metric='logloss', tree_method='hist')
model1.fit(X_train, y_train)



c:\Users\naman\anaconda3\envs\tf_env\lib\site-packages\xgboost\training.py:183: UserWarning: [01:47:44] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=7, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=200, n_jobs=None,
              num_parallel_tree=None, ...)

In [23]:
y_pred = model1.predict(X_test)


In [24]:
print(f" Accuracy: {accuracy:.4f}")

# Print classification report
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Print confusion matrix
print("\n Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

 Accuracy: 0.7590

Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.97      0.83     14907
           1       0.89      0.40      0.55      8971

    accuracy                           0.76     23878
   macro avg       0.81      0.69      0.69     23878
weighted avg       0.79      0.76      0.73     23878


 Confusion Matrix:
 [[14438   469]
 [ 5353  3618]]


In [26]:
from lightgbm import LGBMClassifier

model2 = LGBMClassifier(n_estimators=200, learning_rate=0.1, max_depth=7)
model2.fit(X_train, y_train)



[LightGBM] [Info] Number of positive: 35253, number of negative: 60259
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000645 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 264
[LightGBM] [Info] Number of data points in the train set: 95512, number of used features: 3
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.369095 -> initscore=-0.536101
[LightGBM] [Info] Start training from score -0.536101
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain:

LGBMClassifier(max_depth=7, n_estimators=200)

In [27]:
y_pred = model2.predict(X_test)


In [28]:
print(f" Accuracy: {accuracy:.4f}")

# Print classification report
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Print confusion matrix
print("\n Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

 Accuracy: 0.7590

Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.97      0.83     14907
           1       0.91      0.40      0.56      8971

    accuracy                           0.76     23878
   macro avg       0.82      0.69      0.70     23878
weighted avg       0.80      0.76      0.73     23878


 Confusion Matrix:
 [[14533   374]
 [ 5370  3601]]
